### ISSUE TITLE
linuxtag_2023_python

### ISSUE THREAD

**Issue by GITMichaelK** [elsamuko/linuxtag_2022_python#1]
Thank you for the workshop at Kielux2023. In regards to the [list of topics](https://github.com/elsamuko/linuxtag_2023_python#linuxtag-2023) I'd like to know, if these are options or the full program? Myself would be interested in [venv](https://github.com/elsamuko/linuxtag_2023_python#venv) but not much in most of the other themes.
As there are only few participants allowed, I'm not sure if it makes sense. Any other idea to learn about venv, especially as I'm using python already, having a bunch of pip-packages installed.
Thank you and regards, Michael

**Comment by elsamuko** [comment]
Hi Michael,

the list of topics is the full program, the venv part will be only a short part at the end.  
There is a script, which shows why venv can be useful:  
https://github.com/elsamuko/linuxtag_2023_python/blob/main/run_venv.sh

Regards,
Samuel

**Comment by GITMichaelK** [comment]
Hello Samuel,

thank you for quick response.
To be honest, the script does not explain much to me, but I hope to be aware oft the advantages with an virtual environment. Unfortunately I figured this after having few python-applications running. So I'm searching advice for the proper transformation.

Thanks and good success for you workshop!

Regards
Michael

**Comment by elsamuko** [comment]
The script 
* setups a venv environment
* installs an older version of pip within the venv
* prints pip's version
* and exits the venv again

=> venv is useful if you have to handle packages in different versions, e.g. for web development
